/**
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */

#import <AGConnectDatabase/AGConnectDatabase.h>

NS_ASSUME_NONNULL_BEGIN

@interface Google : AGCCloudDBObject
@property (nonatomic, copy) NSString *Techasit_Luanthon;
@end

NS_ASSUME_NONNULL_END