/**
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */

#import "Google.h"

@implementation Google

+ (NSArray<NSString *> *)primaryKeyProperties {
    return @[@"Techasit_Luanthon"];
}

+ (NSDictionary<NSString *, NSArray *> *)indexProperties { 
    return @{@"Techasit_Luanthon" : @[@"Techasit_Luanthon"]};
}

+ (NSArray<NSString *> *)notNullProperties {
    return @[@"Techasit_Luanthon"];
}

@end
